/**
 * Character sets used across generators
 */
const CHARSETS = {
    LOWERCASE: 'abcdefghijklmnopqrstuvwxyz',
    UPPERCASE: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
    DIGITS: '0123456789',
    SYMBOLS: '!@#$%^&*()_+-=[]{}|;:,.<>?',
    SYMBOLS_SAFE: '!@#$%^&*_+-=',
    HEX: '0123456789abcdef',
    HEX_UPPER: '0123456789ABCDEF',
    BASE62: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789',
    BASE64: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/',
    URL_SAFE: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_',
    ALPHANUMERIC: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789',
};

// Combine charsets
CHARSETS.ALL = CHARSETS.LOWERCASE + CHARSETS.UPPERCASE + CHARSETS.DIGITS + CHARSETS.SYMBOLS;
CHARSETS.ALL_SAFE = CHARSETS.LOWERCASE + CHARSETS.UPPERCASE + CHARSETS.DIGITS + CHARSETS.SYMBOLS_SAFE;

module.exports = CHARSETS;